name: Check

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    name: Cargo check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
            sudo apt update
            sudo apt install -y \
              libwebkit2gtk-4.1-dev \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              xdg-utils \
              lld
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check --locked